name: test

on:
  workflow_dispatch:
    inputs:
      products:
        description: "List of Products"
        default: '["yellow", "red"]'
      limits:
        description: "List of limits"
        default: '[50, 100]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        product: ${{ fromJSON(github.event.inputs.products)}}
        limits: ${{ fromJSON(github.event.inputs.limits) }}
    steps:
      - run: echo "${{ matrix.product }} / ${{ matrix.limits }}"

