name: test

on:
  workflow_dispatch:
    inputs:
      a:
        type: boolean
      b:
        type: boolean
      v:
        type: string
        default: '[1, 2]'
jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: set-matrix
        with:
          script: |
            var types = [];
            if (context.payload.inputs.a) {
              types.push('a')
            }
            if (context.payload.inputs.b) {
              types.push('b')
            }
            var versions = fromJSON(context.payload.inputs.v)
            
            var result = []
            for (t in types) {
              for (v in versions) {
                result.push(t + "-" + v)
              }
            }
            return result

      - name: Debug output
        run: echo "${{ steps.set-matrix.outputs.result }}"
